
# Specifying service: 
service: awesome-api

#other deployment specs 
provider:
  name: aws
  runtime: nodejs12.x
  profile: java_lambda_user

# you can overwrite defaults here
  stage: dev
  region: us-east-1
  
  
  
# api gateway 
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: first-endpoint
          method: get




#Resources
resources:
 Resources:
   uploadBucket:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: ${self:service}-${self:provider.stage}-uploads #we can name simply my-bucket-uploads, instaed if we use ${} we can use servicename-stageName-uploads ( in our case it is going to be awesome-api-dev-uploads )
