
# Specifying service: 
service: awesome-api

#other deployment specs 
provider:
  name: aws
  runtime: nodejs12.x
  profile: java_lambda_user

# you can overwrite defaults here
  stage: dev
  region: us-east-1
